// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio.Repositorio.RepositorioBDD;

namespace Repositorio.Migrations
{
    [DbContext(typeof(EntidadesContexto))]
    partial class EntidadesContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidades.Admin", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsSuperAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Email");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Entidades.Cancion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Duracion")
                        .HasColumnType("real");

                    b.Property<string>("LinkAudio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cancion");
                });

            modelBuilder.Entity("Entidades.Cita", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Descuento")
                        .HasColumnType("real");

                    b.Property<string>("DireccionConsulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DuracionSesionHoras")
                        .HasColumnType("real");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormatoConsulta")
                        .HasColumnType("int");

                    b.Property<int>("IdPsicologo")
                        .HasColumnType("int");

                    b.Property<string>("NombrePsicologo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrecioFinal")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("Entidades.Entidades.Video", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionMins")
                        .HasColumnType("int");

                    b.Property<string>("LinkVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Entidades.GaleriaMusical", b =>
                {
                    b.Property<int>("CategoriaMusical")
                        .HasColumnType("int");

                    b.HasKey("CategoriaMusical");

                    b.ToTable("GaleriaMusical");
                });

            modelBuilder.Entity("Entidades.Playlist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("Entidades.Psicologo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionUrbana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormatoConsulta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrecioHora")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Psicologo");
                });

            modelBuilder.Entity("Entidades.Sesion", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsSuperAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Token");

                    b.ToTable("Sesion");
                });

            modelBuilder.Entity("Repositorio.Repositorio.Logica.Entidades.Credito", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Credito");
                });

            modelBuilder.Entity("Repositorio.Repositorio.RepositorioBDD.Entidades.IXCancionGaleria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDCancion")
                        .HasColumnType("int");

                    b.Property<int>("IDGaleria")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IX_Cancion_Galeria");
                });

            modelBuilder.Entity("Repositorio.Repositorio.RepositorioBDD.Entidades.IXCancionPlayList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDCancion")
                        .HasColumnType("int");

                    b.Property<int>("IDPlayList")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IX_Cancion_PlayList");
                });

            modelBuilder.Entity("Repositorio.Repositorio.RepositorioBDD.Entidades.IXGaleriaPlayList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDGaleria")
                        .HasColumnType("int");

                    b.Property<int>("IDPlaylist")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IX_Galeria_PlayList");
                });

            modelBuilder.Entity("Repositorio.Repositorio.RepositorioBDD.Entidades.IXPsicologoDolencia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDDolencia")
                        .HasColumnType("int");

                    b.Property<int>("IDPsicologo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IX_Psicologo_Dolencia");
                });

            modelBuilder.Entity("Repositorio.Repositorio.RepositorioBDD.Entidades.IXVideoGaleria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDGaleria")
                        .HasColumnType("int");

                    b.Property<int>("IDVideo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IX_Video_Galeria");
                });

            modelBuilder.Entity("Repositorio.Repositorio.RepositorioBDD.Entidades.IXVideoPlayList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDPlayList")
                        .HasColumnType("int");

                    b.Property<int>("IDVideo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IX_Video_PlayList");
                });

            modelBuilder.Entity("Web.Api.Entidades.Descuento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Descuento");
                });
#pragma warning restore 612, 618
        }
    }
}
